### ISSUE TITLE
Error: Unable to parse data

### ISSUE THREAD

**Issue by phil-lipp** [jonalaniz/NextStats#10]
I'm not sure if there are still plans to update this, but at least until NC 28 I personally didn't see any reason to. However now I'm getting the error message 'Unable to parse data' after tapping on my server on the main screen.

Nextcloud version: 28.0.2
iOS Version: 17.3

**Comment by jonalaniz** [comment]
Fix was just pushed to main, this same binary was also just pushed to AppStoreConnect and is awaiting release.
