### ISSUE TITLE
Unexpected Response (<NSHTTPURLResponse:...

### ISSUE THREAD

**Issue by pyyhttu** [jonalaniz/NextStats#19]
Nextstats version 3.0.8, although I believe error  started sometime in/after version 3.0.5.

I have Nextcloud installed to a sub-folder.

When I try to setup a new server entry (new phone), I get an error: `Unexpected Response (<NSHTTPURLResponse:...`

![Photo_2024-12-14_4343](https://github.com/user-attachments/assets/34f8974d-4c73-4b14-a896-a4d4a416db05)

I also tried to populate Server URL: without the sub-folder, same error.

**Update:** I still have my old phone with existing Nextstats entry, here's the full error output from there: `Unexpected Response (<NSHTTPURLResponse: 0x303fb60c0>`:

![Photo_2024-12-14_4291](https://github.com/user-attachments/assets/203c0bf8-0f54-4a81-b992-e20e7e520af1)

**Comment by jonalaniz** [comment]
Thanks, I modified the way it builds urls a while back and it removed the entire path component.

I have modified the way it builds urls to account for subfolders and it is in the latest build. I am waiting for App Review to approve it.

**Comment by pyyhttu** [comment]
App store updated. Tested and works. Thanks!
