### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by toughIQ** [jonalaniz/NextStats#2]
I get a JSON error when connecting. 
![Image](https://i.imgur.com/KqoZQYl.jpg)
Why and how to fix this?
Thanks

**Comment by jonalaniz** [comment]
Can you send me the JSON output from your server? It can be found at <yourserveraddress>/ocs/v2.php/apps/serverinfo/api/v1/info?format=json

The file doesn’t contain any identifying information, I just want to test the JSON output and see if there’s something parsing incorrectly in the app.

Thanks!

**Comment by toughIQ** [comment]
`{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"nextcloud":{"system":{"version":"18.0.3.0","theme":"","enable_avatars":"no","enable_previews":"yes","memcache.local":"\\OC\\Memcache\\APCu","memcache.distributed":"\\OC\\Memcache\\Redis","filelocking.enabled":"yes","memcache.locking":"\\OC\\Memcache\\Redis","debug":"no","freespace":240350789632,"cpuload":[0.12,0.42,0.52],"mem_total":"N\/A","mem_free":"N\/A","swap_total":"N\/A","swap_free":"N\/A","apps":{"num_installed":50,"num_updates_available":0,"app_updates":[]}},"storage":{"num_users":344,"num_files":1948017,"num_storages":4195,"num_storages_local":2510,"num_storages_home":987,"num_storages_other":698},"shares":{"num_shares":776,"num_shares_user":301,"num_shares_groups":17,"num_shares_link":429,"num_shares_mail":14,"num_shares_room":0,"num_shares_link_no_password":429,"num_fed_shares_sent":6,"num_fed_shares_received":4,"permissions_2_0":"3","permissions_0_1":"13","permissions_1_1":"2","permissions_2_1":"2","permissions_3_1":"404","permissions_4_1":"9","permissions_6_1":"1","permissions_0_3":"1","permissions_3_3":"2","permissions_4_3":"3","permissions_3_4":"3","permissions_3_5":"3","permissions_0_7":"1","permissions_0_15":"8","permissions_1_15":"1","permissions_2_15":"1","permissions_3_15":"17","permissions_0_17":"17","permissions_1_17":"6","permissions_6_17":"1","permissions_0_19":"131","permissions_1_19":"1","permissions_2_19":"2","permissions_1_23":"1","permissions_0_27":"5","permissions_0_31":"125","permissions_1_31":"6","permissions_2_31":"1","permissions_4_31":"2","permissions_6_31":"4"}},"server":{"webserver":"nginx\/1.14.0","php":{"version":"7.2.31","memory_limit":1073741824,"max_execution_time":3600,"upload_max_filesize":6442450944},"database":{"type":"mysql","version":"5.7.29","size":2091679744}},"activeUsers":{"last5minutes":13,"last1hour":15,"last24hours":20}}}}`

**Comment by jonalaniz** [comment]
Sorry for getting to this late, internet has been down since yesterday over here. Working on a fix for this, the app expects an int for the memory values, but is getting "N/A".

Just curious, is there a special configuration or something that would make your server not report memory and swap info? This is the second instance I have seen this issue.

**Comment by toughIQ** [comment]
I think I found the reason.
Memory Data is fetched via` /proc/meminfo`
https://github.com/nextcloud/serverinfo/blob/master/lib/SystemStatistics.php#L97

But `/proc` was/is not within the php setting `open_basedir`
So the ServerInfo App cannot fetch this info, since it doesnt get access to this directory.

I am not sure if it is wise, to add `/proc` to the `open_basedir`.

**UPDATE:** found this article:
https://help.nextcloud.com/t/nextcloud-13-memory-info-not-available/27134/7
Just added `/proc/meminfo` to `open_basedir`. So the `/proc` directory does not get exposed entirely.

**Comment by jonalaniz** [comment]
I actually just pushed an update here that accounts for servers that cannot fetch Memory Data. I have committed it to the repository, but it may be a while until Apple approves this update. I am still waiting on approval for a previous update. I'll keep this open until you are able to test this yourself.
