### ISSUE TITLE
Cannot add server

### ISSUE THREAD

**Issue by ItzYanick** [jonalaniz/NextStats#7]
Everytime I try to add a server to the App I go through the auth flow and end up on a screen saying: "Your client should now be connected! You can close this window.". But when I close the window it does not show the server in the list

**Comment by jonalaniz** [comment]
What version of Nextcloud are you running? NextStats polls your server for login credentials while you are signing in through the web view. The page automatically closes when the app authenticates and adds a new server when the credentials are captured.

**Comment by ItzYanick** [comment]
I am running on 21.0.3. How often does it poll?

**Comment by jonalaniz** [comment]
Once the login page is opened it begins polling the endpoint every 2 seconds.

**Comment by ItzYanick** [comment]
whats the endpoint?

**Comment by jonalaniz** [comment]
https:/[yourserver.com]/index.php/login/v2/poll

**Comment by ItzYanick** [comment]
okay i activated the access log of my nginx server for testing purposes. When i try to hit the endpoint in my browser (just to check if not my reverse proxy is messing up) it shows up there. But my iPhone is not showing up there.

**Comment by ItzYanick** [comment]
okay update. i redid it with the access log activated.
```
10.10.5.200 - - [10/Jul/2021:21:56:12 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:15 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:17 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:19 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:21 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:23 +0000] "POST /login HTTP/1.1" 303 0 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
10.10.5.200 - - [10/Jul/2021:21:56:23 +0000] "GET /login/v2/grant?stateToken=djbc9lCvOEsRi8usjgSCfb2nuYFpBIHxaZVYZrca0vAINnDvq9KQkr1RRUJRSJWo HTTP/1.1" 200 3731 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
10.10.5.200 - - [10/Jul/2021:21:56:23 +0000] "GET /apps/accessibility/css/user-c470bd34ef01903873dfb30df27ebb81 HTTP/1.1" 200 3864 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
10.10.5.200 - - [10/Jul/2021:21:56:24 +0000] "POST /login/v2/poll HTTP/1.1" 404 2 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:25 +0000] "POST /login/v2/grant HTTP/1.1" 200 3514 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
10.10.5.200 - - [10/Jul/2021:21:56:26 +0000] "POST /login/v2/poll HTTP/1.1" 200 164 "-" "NextStats for iOS"
10.10.5.200 - - [10/Jul/2021:21:56:26 +0000] "GET /index.php/apps/theming/image/logo HTTP/1.1" 200 870 "-" "NextStats for iOS"
```
for me this looks like the app gets the poll but does not do anything

**Comment by jonalaniz** [comment]
Can you check in your nextcloud under Settings > Personal > Security > Devices & sessions and verify that "NextStats for iOS" shows up. 

If this shows up, then I believe there is an issue in saving app password credentials. Thanks.

**Comment by ItzYanick** [comment]
![image](https://user-images.githubusercontent.com/18502828/125180577-da461900-e1fb-11eb-8fd1-293452e8e22b.png)

**Comment by jonalaniz** [comment]
Alright, thanks. If you can give me a copy of the JSON file located at the following endpoint I can recreate your server environment and try to duplicate the issue on my end for debugging. 

https://[yourserver.com]/ocs/v2.php/apps/serverinfo/api/v1/info?format=json

**Comment by ItzYanick** [comment]
Okay! I've put it on Hastebin: [https://hatebin.com/qvuqdzwveo](https://hatebin.com/qvuqdzwveo)

**Comment by jonalaniz** [comment]
Does your server have a custom logo?

**Comment by ItzYanick** [comment]
yep. why?

**Comment by ItzYanick** [comment]
It is a SVG File tho

**Comment by jonalaniz** [comment]
I was able to replicate the issue and it looks like the culprit was in the way it checks for and saves custom logos. If the logo could not be converted into a UIImage, it would not close the window and save the credentials. I have corrected this issue in my latest commit. Are you able to test builds from source? If not, I have submitted this new build to the App Store and am awaiting approval.

**Comment by ItzYanick** [comment]
If you have a unsigned IPA file I can test it out.

**Comment by jonalaniz** [comment]
I actually had the review process expedited. It's in the App Store if you would like to test it out.

**Comment by ItzYanick** [comment]
okay i just downloaded the update and everything seems to work now! I added it and I see all the stats :D
thanks for the quick bux fix. Always happy to see how one line of code can mess up this bad haha.

It now shows me a generic Image (i guess) it would be great to see if u could add the feature that it could convert a svg image to a UIImage or to add a custom image in the App (to overwrite the one) but that isnt really a top priority. I am just glad it works now ^^

**Comment by jonalaniz** [comment]
Yeah that's definitely in the works. I'm glad it's all fixed! Thanks for helping me out.
