### ISSUE TITLE
Nextcloud server not found

### ISSUE THREAD

**Issue by pyyhttu** [jonalaniz/NextStats#9]
Updated iOS Nextstat today to v. 2.1 which resulted my server not being able to be displayed anymore in NextStats (error message mentioned 404).

I proceeded to remove the server to add it again in NextStats, but adding the server URL with the same I had previously working, results now in an error "Nextcloud server not found, please check url."

Couple of things to note:
- I have TOTP enabled
- I've installed Nextcloud on a shared hosting, and in subdomain and subfolder there (https://subdomain.domain.fi/nextcloud). https is enabled.

How should I troubleshoot this?

**Comment by pyyhttu** [comment]
Updated NextStats to 2.2.1. I'm now able to add the server, but accessing the entry results in an error: Unauthorized (404), screenshot [here](https://imgur.com/a/PVeD760). Checked nextcloud.log and this error does not get registered there.

And clarification on my subdomain naming scheme: I have it defined with dash (-) as https://sub-domain.domain.fi/nextcloud

**Comment by jonalaniz** [comment]
Sorry for the delay. I went ahead and put together a nextcloud instance on a subdomain with TOTP enabled for troubleshooting this weekend and I believe I have the issue fixed. Can you share your server config just so I can match yours and test before pushing out the update?

**Comment by pyyhttu** [comment]
I believe you already got it right. Updated this morning NextStats to 2.1.2 and I'm able to pull the data for my instance correctly: https://imgur.com/a/tcO4gIY
